In [1]:
import pandas as pd
from epytope.Core import AntigenImmuneReceptor
from epytope.Core import ImmuneReceptorChain
from epytope.TCRSimilarityMeasurement import SimilarityTools, TCRSimilarityMeasurementFactory
from epytope.IO.FileReader import process_dataset_TCR

### Initialize TCR objects

In [2]:
TRA1 = ImmuneReceptorChain(chain_type="TRA", v_gene="TRAV7-3*01", d_gene="", j_gene="TRAJ33*01",
                                 cdr3="CAVSLDSNYQLIW", nuc_seq="tgtgcagtgagcctcgatagcaactatcagttgatctgg")
TRB1 = ImmuneReceptorChain(chain_type="TRB", v_gene="TRBV13-1", d_gene="", j_gene="TRAJ33*01",
                        cdr3="CASSDFDWGGDAETLYF", nuc_seq="tgtgccagcagtgatttcgactggggaggggatgcagaaacgctgtatttt")
TRA2 = ImmuneReceptorChain(chain_type="TRA", v_gene="TRAV6D-6*01", d_gene="", j_gene="TRAJ56*01",
                           cdr3="CALGDRATGGNNKLTF", nuc_seq="tgtgctctgggtgacagggctactggaggcaataataagctgactttt")
TRB2 = ImmuneReceptorChain(chain_type="TRB", v_gene="TRBV29*01", d_gene="", j_gene="TRBJ1-1*01",
                           cdr3="CASSPDRGEVFF")
TRA3 = ImmuneReceptorChain(chain_type="TRA", v_gene="TRAV6D-6", d_gene="", j_gene="TRAJ49*01",
                           cdr3="CALGSNTGYQNFYF")
TRB3 = ImmuneReceptorChain(chain_type="TRB", v_gene="TRBV29", d_gene="", j_gene="TRBJ1-5*01",
                           cdr3="CASTGGGAPLF")
TRA4 = ImmuneReceptorChain(chain_type="TRA", v_gene="TRAV6-4*01", d_gene="", j_gene="TRAJ34*02",
                           cdr3="CALAPSNTNKVVF")
TRB4 = ImmuneReceptorChain(chain_type="TRB", v_gene="TRBV2*01", d_gene="", j_gene="TRBJ2-7*01",
                           cdr3="CASSQDPGDYEQYF")
TCR1 = AntigenImmuneReceptor(receptor_id="1", chains=[TRA1, TRB1], species="mouse")
TCR2 = AntigenImmuneReceptor(receptor_id="2", chains=[TRA2, TRB2], species="mouse")
TCR3 = AntigenImmuneReceptor(receptor_id="3", chains=[TRA3, TRB3], species="mouse")
TCR4 = AntigenImmuneReceptor(receptor_id="4", chains=[TRA4, TRB4], species="mouse")
TCR5 = AntigenImmuneReceptor(receptor_id="1", chains=[TRB4], species="mouse")
rep1 = [TCR1, TCR2]
rep2 = [TCR3, TCR4]
path1 = "/home/mahmoud/Documents/example.csv"
df1 = pd.read_csv("/home/mahmoud/Downloads/dash.csv").head(5)
path2 = "/home/mahmoud/Documents/example2.csv"
df2 = pd.read_csv("/home/mahmoud/Downloads/dash.csv").iloc[6:8, ]

In [25]:
df1

,subject,epitope,count,v_a_gene,j_a_gene,cdr3_a_aa,cdr3_a_nucseq,v_b_gene,j_b_gene,cdr3_b_aa,cdr3_b_nucseq,clone_id
0,mouse_subject0050,PA,2,TRAV7-3*01,TRAJ33*01,CAVSLDSNYQLIW,tgtgcagtgagcctcgatagcaactatcagttgatctgg,TRBV13-1*01,TRBJ2-3*01,CASSDFDWGGDAETLYF,tgtgccagcagtgatttcgactggggaggggatgcagaaacgctgt...,mouse_tcr0072.clone
1,mouse_subject0050,PA,6,TRAV6D-6*01,TRAJ56*01,CALGDRATGGNNKLTF,tgtgctctgggtgacagggctactggaggcaataataagctgactttt,TRBV29*01,TRBJ1-1*01,CASSPDRGEVFF,tgtgctagcagtccggacaggggtgaagtcttcttt,mouse_tcr0096.clone
2,mouse_subject0050,PA,1,TRAV6D-6*01,TRAJ49*01,CALGSNTGYQNFYF,tgtgctctgggctcgaacacgggttaccagaacttctatttt,TRBV29*01,TRBJ1-5*01,CASTGGGAPLF,tgtgctagcacagggggaggggctccgcttttt,mouse_tcr0276.clone
3,mouse_subject0050,PA,2,TRAV6-4*01,TRAJ34*02,CALAPSNTNKVVF,tgtgctctggccccttccaataccaacaaagtcgtcttt,TRBV2*01,TRBJ2-7*01,CASSQDPGDYEQYF,tgtgccagcagccaagatcctggggactatgaacagtacttc,mouse_tcr0269.clone
4,mouse_subject0050,PA,1,TRAV6-4*01,TRAJ34*02,CALVPSNTNKVVF,tgtgctctggtcccttccaataccaacaaagtcgtcttt,TRBV29*01,TRBJ2-4*01,CASSLGGENTLYF,tgtgctagcagtttagggggggaaaacaccttgtacttt,mouse_tcr0285.clone

In [26]:
df2

,subject,epitope,count,v_a_gene,j_a_gene,cdr3_a_aa,cdr3_a_nucseq,v_b_gene,j_b_gene,cdr3_b_aa,cdr3_b_nucseq,clone_id
6,mouse_subject0050,PA,1,TRAV21/DV12*01,TRAJ56*01,CILRVGATGGNNKLTL,tgtatcctgagagtaggggctactggaggcaataataagctgactctt,TRBV29*01,TRBJ1-1*01,CASSLDRGEVFF,tgtgctagcagtttggacaggggtgaagtcttcttt,mouse_tcr0167.clone
7,mouse_subject0050,PA,1,TRAV6-4*01,TRAJ34*02,CALVPSNTNKVVF,tgtgctctggttccttccaataccaacaaagtcgtcttt,TRBV29*01,TRBJ2-7*01,CASSLSGYEQYF,tgtgctagcagtttatccggatatgaacagtacttc,mouse_tcr0234.clone

### Display all available similarity methods

In [3]:
for m in TCRSimilarityMeasurementFactory.available_methods():
    print(m)

tcrdist3

### Initialize an object for tcrdist3 method

In [3]:
mo = TCRSimilarityMeasurementFactory("tcrdist3")

### TCR similarity for one repertoire: default parameters
#### TCR similarity for alpha seqs

In [6]:
result = mo.compute_distance(rep1=rep1, organism="mouse", seq_type="ALPHA")
result

Method                                                                                             tcrdist3  \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
1                2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF         34

Method
Chain                                                                                              alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
1                2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF     158

#### TCR similarity for beta seqs

In [7]:
result = mo.compute_distance(rep1=rep2, organism="mouse", seq_type="beta")
result

Method                                                                                        tcrdist3  \
Chain                                                                                           cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF       35

Method
Chain                                                                                         beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF  153

#### TCR similarity for alpha and beta seqs

In [8]:
result = mo.compute_distance(rep1=rep2, organism="mouse", seq_type="alphabeta")
result

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/tcrdist/repertoire.py:159: UserWarning: cell_df needs a counts column to track clonal number of frequency

  self._validate_cell_df()
/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/tcrdist/repertoire.py:791: UserWarning: No 'count' column provided; count column set to 1
  warnings.warn("No 'count' column provided; count column set to 1")

Method                                                                                        tcrdist3  \
Chain                                                                                           cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF       35

Method                                                                                                \
Chain                                                                                         cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF     35

Method                                                                                               \
Chain                                                                                         alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF   135

Method
Chain                                                                                         beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
3                4                CALGSNTGYQNFYF CASTGGGAPLF    CALAPSNTNKVVF  CASSQDPGDYEQYF  153

### Using another metrics
#### TCR similarity for alpha and beta seqs combined

In [9]:
result = mo.compute_distance(rep1=rep1, organism="mouse", seq_type="both", default=False,
                                metric='nw_metric', open=1, extend=1)
result

Method                                                                                             tcrdist3  \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
1                2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF        129

Method                                                                                                     \
Chain                                                                                              cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
1                2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      105

Method
Chain                                                                                              alpha+beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
1                2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF          702

### TCR similarity for tow repertoires

In [11]:
result = mo.compute_distance(rep1=rep1, rep2=rep2, organism="mouse", seq_type="alphabeta", default=False,
                                metric='nb_vector_hamming_distance')
result

Method                                                                                             tcrdist3  \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a) (Rep2, cdr3_b)
1                3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF CASTGGGAPLF           9
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF  CASSQDPGDYEQYF       11
2                3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF CASTGGGAPLF           9
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF  CASSQDPGDYEQYF        9

Method                                                                                                     \
Chain                                                                                              cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a) (Rep2, cdr3_b)
1                3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF CASTGGGAPLF         8
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF  CASSQDPGDYEQYF     10
2                3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF CASTGGGAPLF         7
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF  CASSQDPGDYEQYF      6

Method                                                                                                    \
Chain                                                                                              alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a) (Rep2, cdr3_b)
1                3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF CASTGGGAPLF       27
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF  CASSQDPGDYEQYF    33
2                3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF CASTGGGAPLF       27
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF  CASSQDPGDYEQYF    27

Method
Chain                                                                                              beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a) (Rep2, cdr3_b)
1                3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF CASTGGGAPLF      24
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF  CASSQDPGDYEQYF   30
2                3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF CASTGGGAPLF      21
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF  CASSQDPGDYEQYF   18

### TCR similarity for one dataset
#### Passing the dataset as dataframe object

In [14]:
result = mo.compute_distance_from_dataset(df1=df1, organism="mouse", seq_type="ALPHA", default=False,
                                             metric='nw_hamming_metric', open=2, extend=2, source="dash")
result

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF         12
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF           9
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF       10
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF        10
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF           8
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF        9
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF        10
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF        8
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF         8
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF         1

Method
Chain                                                                                                alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      36
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF       27
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF    30
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF     30
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF       24
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF    27
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF     30
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF    24
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF     24
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF      3

#### Passing the dataframe as a path

In [16]:
result = mo.compute_distance_from_dataset(path1=path2, organism="mouse", seq_type="ALPHAbeta", source="dash")
result

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/tcrdist/repertoire.py:159: UserWarning: cell_df needs a counts column to track clonal number of frequency

  self._validate_cell_df()
/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/tcrdist/repertoire.py:791: UserWarning: No 'count' column provided; count column set to 1
  warnings.warn("No 'count' column provided; count column set to 1")

Method                                                                                           tcrdist3  \
Chain                                                                                              cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)  (Rep1, cdr3_b)  (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                1                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVNSNYQLIW     CAWSGDSAETLYF        28
                 2                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSPSGSWQLIF   CASGDLREEDTQYF       12
                 3                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSSNYNVLYF    CASSGTSAETLYF        32
                 4                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAAVNTGNYKYVF   CASTKSNTEVFF         31
                 5                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSADNYAQGLTF  CASSWDSAETLYF        30
...                                                                                                   ...
45               47               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CATDAATQVVGQLTF CASSLTSNSDYTF        36
                 48               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CAARSGGSSGNKLIF CASSLLGDSYEQYF       31
46               47               CAATGGNTGKLIF   CASSSMGGSAETLYF CATDAATQVVGQLTF CASSLTSNSDYTF        31
                 48               CAATGGNTGKLIF   CASSSMGGSAETLYF CAARSGGSSGNKLIF CASSLLGDSYEQYF       27
47               48               CATDAATQVVGQLTF CASSLTSNSDYTF   CAARSGGSSGNKLIF CASSLLGDSYEQYF       34

Method                                                                                                   \
Chain                                                                                            cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)  (Rep1, cdr3_b)  (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                1                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVNSNYQLIW     CAWSGDSAETLYF      27
                 2                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSPSGSWQLIF   CASGDLREEDTQYF     36
                 3                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSSNYNVLYF    CASSGTSAETLYF      27
                 4                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAAVNTGNYKYVF   CASTKSNTEVFF       15
                 5                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSADNYAQGLTF  CASSWDSAETLYF      27
...                                                                                                 ...
45               47               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CATDAATQVVGQLTF CASSLTSNSDYTF      29
                 48               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CAARSGGSSGNKLIF CASSLLGDSYEQYF     12
46               47               CAATGGNTGKLIF   CASSSMGGSAETLYF CATDAATQVVGQLTF CASSLTSNSDYTF      32
                 48               CAATGGNTGKLIF   CASSSMGGSAETLYF CAARSGGSSGNKLIF CASSLLGDSYEQYF     26
47               48               CATDAATQVVGQLTF CASSLTSNSDYTF   CAARSGGSSGNKLIF CASSLLGDSYEQYF     25

Method                                                                                                  \
Chain                                                                                            alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)  (Rep1, cdr3_b)  (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                1                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVNSNYQLIW     CAWSGDSAETLYF    139
                 2                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSPSGSWQLIF   CASGDLREEDTQYF    91
                 3                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSSNYNVLYF    CASSGTSAETLYF    151
                 4                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAAVNTGNYKYVF   CASTKSNTEVFF     152
                 5                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSADNYAQGLTF  CASSWDSAETLYF    145
...                                                                                                ...
45               47               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CATDAATQVVGQLTF CASSLTSNSDYTF    162
                 48               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CAARSGGSSGNKLIF CASSLLGDSYEQYF   150
46               47               CAATGGNTGKLIF   CASSSMGGSAETLYF CATDAATQVVGQLTF CASSLTSNSDYTF    146
                 48               CAATGGNTGKLIF   CASSSMGGSAETLYF CAARSGGSSGNKLIF CASSLLGDSYEQYF    91
47               48               CATDAATQVVGQLTF CASSLTSNSDYTF   CAARSGGSSGNKLIF CASSLLGDSYEQYF   159

Method
Chain                                                                                            beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)  (Rep1, cdr3_b)  (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                1                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVNSNYQLIW     CAWSGDSAETLYF   133
                 2                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSPSGSWQLIF   CASGDLREEDTQYF  154
                 3                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSSNYNVLYF    CASSGTSAETLYF   116
                 4                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAAVNTGNYKYVF   CASTKSNTEVFF     88
                 5                CAVSYASSGSWQLIF CASSSRGSNTEVFF  CAVSADNYAQGLTF  CASSWDSAETLYF   119
...                                                                                               ...
45               47               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CATDAATQVVGQLTF CASSLTSNSDYTF    87
                 48               CAVRDRNYAQGLTF  CASSLELGDYAEQFF CAARSGGSSGNKLIF CASSLLGDSYEQYF   36
46               47               CAATGGNTGKLIF   CASSSMGGSAETLYF CATDAATQVVGQLTF CASSLTSNSDYTF   139
                 48               CAATGGNTGKLIF   CASSSMGGSAETLYF CAARSGGSSGNKLIF CASSLLGDSYEQYF  121
47               48               CATDAATQVVGQLTF CASSLTSNSDYTF   CAARSGGSSGNKLIF CASSLLGDSYEQYF   75

[1176 rows x 4 columns]

### TCR similarity for tow datasets
#### Passing the datasets as dataframes

In [18]:
result = mo.compute_distance_from_dataset(df1=df1, df2=df2, organism="mouse", seq_type="BOTH",
                                             default=False, metric='nb_vector_editdistance', source="dash")
result

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CILRVGATGGNNKLTL CASSLDRGEVFF         42
                 1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLSGYEQYF         36
1                0                CALGDRATGGNNKLTF CASSPDRGEVFF      CILRVGATGGNNKLTL CASSLDRGEVFF         20
                 1                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF         35
2                0                CALGSNTGYQNFYF   CASTGGGAPLF       CILRVGATGGNNKLTL CASSLDRGEVFF         39
                 1                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLSGYEQYF         31
3                0                CALAPSNTNKVVF    CASSQDPGDYEQYF    CILRVGATGGNNKLTL CASSLDRGEVFF         39
                 1                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLSGYEQYF          4
4                0                CALVPSNTNKVVF    CASSLGGENTLYF     CILRVGATGGNNKLTL CASSLDRGEVFF         38
                 1                CALVPSNTNKVVF    CASSLGGENTLYF     CALVPSNTNKVVF    CASSLSGYEQYF          0

Method                                                                                                       \
Chain                                                                                                cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CILRVGATGGNNKLTL CASSLDRGEVFF       32
                 1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLSGYEQYF       36
1                0                CALGDRATGGNNKLTF CASSPDRGEVFF      CILRVGATGGNNKLTL CASSLDRGEVFF        4
                 1                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF       21
2                0                CALGSNTGYQNFYF   CASTGGGAPLF       CILRVGATGGNNKLTL CASSLDRGEVFF       27
                 1                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLSGYEQYF       27
3                0                CALAPSNTNKVVF    CASSQDPGDYEQYF    CILRVGATGGNNKLTL CASSLDRGEVFF       21
                 1                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLSGYEQYF       16
4                0                CALVPSNTNKVVF    CASSLGGENTLYF     CILRVGATGGNNKLTL CASSLDRGEVFF       20
                 1                CALVPSNTNKVVF    CASSLGGENTLYF     CALVPSNTNKVVF    CASSLSGYEQYF       20

Method
Chain                                                                                                alpha+beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CILRVGATGGNNKLTL CASSLDRGEVFF          222
                 1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLSGYEQYF          216
1                0                CALGDRATGGNNKLTF CASSPDRGEVFF      CILRVGATGGNNKLTL CASSLDRGEVFF           72
                 1                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF          168
2                0                CALGSNTGYQNFYF   CASTGGGAPLF       CILRVGATGGNNKLTL CASSLDRGEVFF          198
                 1                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLSGYEQYF          174
3                0                CALAPSNTNKVVF    CASSQDPGDYEQYF    CILRVGATGGNNKLTL CASSLDRGEVFF          180
                 1                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLSGYEQYF           60
4                0                CALVPSNTNKVVF    CASSLGGENTLYF     CILRVGATGGNNKLTL CASSLDRGEVFF          174
                 1                CALVPSNTNKVVF    CASSLGGENTLYF     CALVPSNTNKVVF    CASSLSGYEQYF           60

#### Passing the datasets as paths

In [20]:
result = mo.compute_distance_from_dataset(path1=path1, path2=path2, organism="mouse", seq_type="alphabeta",
                                             default=False, metric='nb_vector_editdistance', source="dash")
result

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                             tcrdist3  \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSYASSGSWQLIF CASSSRGSNTEVFF        21
                 1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVNSNYQLIW     CAWSGDSAETLYF         11
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSPSGSWQLIF   CASGDLREEDTQYF        20
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSSNYNVLYF    CASSGTSAETLYF         20
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAAVNTGNYKYVF   CASTKSNTEVFF          31
...                                                                                                     ...
96               44               CAVSDNYAQGLTF  CASSFRDSAETLYF    CALSDPSNMGYKLTF CASSLRGDNSPLYF        27
                 45               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAVRDRNYAQGLTF  CASSLELGDYAEQFF        8
                 46               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAATGGNTGKLIF   CASSSMGGSAETLYF       35
                 47               CAVSDNYAQGLTF  CASSFRDSAETLYF    CATDAATQVVGQLTF CASSLTSNSDYTF         31
                 48               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAARSGGSSGNKLIF CASSLLGDSYEQYF        39

Method                                                                                                     \
Chain                                                                                              cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSYASSGSWQLIF CASSSRGSNTEVFF      35
                 1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVNSNYQLIW     CAWSGDSAETLYF       28
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSPSGSWQLIF   CASGDLREEDTQYF      36
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSSNYNVLYF    CASSGTSAETLYF       24
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAAVNTGNYKYVF   CASTKSNTEVFF        42
...                                                                                                   ...
96               44               CAVSDNYAQGLTF  CASSFRDSAETLYF    CALSDPSNMGYKLTF CASSLRGDNSPLYF      24
                 45               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAVRDRNYAQGLTF  CASSLELGDYAEQFF     29
                 46               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAATGGNTGKLIF   CASSSMGGSAETLYF     16
                 47               CAVSDNYAQGLTF  CASSFRDSAETLYF    CATDAATQVVGQLTF CASSLTSNSDYTF       31
                 48               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAARSGGSSGNKLIF CASSLLGDSYEQYF      31

Method                                                                                                    \
Chain                                                                                              alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSYASSGSWQLIF CASSSRGSNTEVFF     63
                 1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVNSNYQLIW     CAWSGDSAETLYF      33
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSPSGSWQLIF   CASGDLREEDTQYF     60
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSSNYNVLYF    CASSGTSAETLYF      60
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAAVNTGNYKYVF   CASTKSNTEVFF       93
...                                                                                                  ...
96               44               CAVSDNYAQGLTF  CASSFRDSAETLYF    CALSDPSNMGYKLTF CASSLRGDNSPLYF     81
                 45               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAVRDRNYAQGLTF  CASSLELGDYAEQFF    24
                 46               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAATGGNTGKLIF   CASSSMGGSAETLYF   105
                 47               CAVSDNYAQGLTF  CASSFRDSAETLYF    CATDAATQVVGQLTF CASSLTSNSDYTF      93
                 48               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAARSGGSSGNKLIF CASSLLGDSYEQYF    117

Method
Chain                                                                                              beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)  (Rep2, cdr3_b)
0                0                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSYASSGSWQLIF CASSSRGSNTEVFF   105
                 1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVNSNYQLIW     CAWSGDSAETLYF     84
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSPSGSWQLIF   CASGDLREEDTQYF   108
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAVSSNYNVLYF    CASSGTSAETLYF     72
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CAAVNTGNYKYVF   CASTKSNTEVFF     126
...                                                                                                 ...
96               44               CAVSDNYAQGLTF  CASSFRDSAETLYF    CALSDPSNMGYKLTF CASSLRGDNSPLYF    72
                 45               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAVRDRNYAQGLTF  CASSLELGDYAEQFF   87
                 46               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAATGGNTGKLIF   CASSSMGGSAETLYF   48
                 47               CAVSDNYAQGLTF  CASSFRDSAETLYF    CATDAATQVVGQLTF CASSLTSNSDYTF     93
                 48               CAVSDNYAQGLTF  CASSFRDSAETLYF    CAARSGGSSGNKLIF CASSLLGDSYEQYF    93

[4753 rows x 4 columns]

### Merging

In [22]:
result1 = mo.compute_distance_from_dataset(df1=df1, organism="mouse", seq_type="BETA", source="dash")
result2 = mo.compute_distance_from_dataset(df1=df1, organism="mouse", seq_type="ALPHA", source="dash")
result1.merge_results(result2)

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF         39
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF          47
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF       44
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF        32
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF          23
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF       24
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF        27
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF       35
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF        27
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF        26

Method                                                                                                     \
Chain                                                                                                beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF    159
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF     183
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF  186
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF   138
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF      69
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF  120
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF    81
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF  153
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF    81
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF   126

Method                                                                                                       \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF       34
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF        34
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF     28
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF      29
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF        36
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF     31
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF      31
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF     35
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF      35
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF       4

Method
Chain                                                                                                alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF     158
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF      158
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF   140
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF    143
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF      108
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF   123
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF    123
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF   135
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF    135
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF     12

### Merging results with different indices

In [9]:
result1 = mo.compute_distance_from_dataset(df1=df1, organism="mouse", seq_type="ALPHA", default=False,
                                             metric='nw_hamming_metric', open=2, extend=2, source="dash")
result1

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF         12
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF           9
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF       10
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF        10
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF           8
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF        9
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF        10
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF        8
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF         8
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF         1

Method
Chain                                                                                                alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      36
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF       27
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF    30
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF     30
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF       24
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF    27
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF     30
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF    24
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF     24
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF      3

In [10]:
result2 = mo.compute_distance_from_dataset(df1=df2, organism="mouse", seq_type="ALPHA", default=False,
                                             metric='nw_hamming_metric', open=2, extend=2, source="dash")
result2

/home/mahmoud/anaconda3/envs/venv2/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

Method                                                                                          tcrdist3  \
Chain                                                                                             cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
0                1                CILRVGATGGNNKLTL CASSLDRGEVFF   CALVPSNTNKVVF  CASSLSGYEQYF         11

Method
Chain                                                                                           alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b) (Rep2, cdr3_a) (Rep2, cdr3_b)
0                1                CILRVGATGGNNKLTL CASSLDRGEVFF   CALVPSNTNKVVF  CASSLSGYEQYF      33

In [12]:
result1.merge_results(result2)

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF       12.0
                                  CILRVGATGGNNKLTL CASSLDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF        NaN
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF         9.0
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF     10.0
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF      10.0
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF         8.0
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF      9.0
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF      10.0
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF      8.0
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF       8.0
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF       1.0

Method                                                                                                      \
Chain                                                                                                alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF    36.0
                                  CILRVGATGGNNKLTL CASSLDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF     NaN
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF     27.0
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF  30.0
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF   30.0
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF     24.0
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF  27.0
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF   30.0
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF  24.0
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF   24.0
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF    3.0

Method                                                                                                       \
Chain                                                                                                cdr3_a
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      NaN
                                  CILRVGATGGNNKLTL CASSLDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF     11.0
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF       NaN
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF    NaN
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF     NaN
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF       NaN
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF    NaN
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF     NaN
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF    NaN
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF     NaN
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF     NaN

Method
Chain                                                                                                alpha
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a)   (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF     NaN
                                  CILRVGATGGNNKLTL CASSLDRGEVFF      CALVPSNTNKVVF    CASSLSGYEQYF    33.0
                 2                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF      NaN
                 3                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF   NaN
                 4                CAVSLDSNYQLIW    CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF    NaN
1                2                CALGDRATGGNNKLTF CASSPDRGEVFF      CALGSNTGYQNFYF   CASTGGGAPLF      NaN
                 3                CALGDRATGGNNKLTF CASSPDRGEVFF      CALAPSNTNKVVF    CASSQDPGDYEQYF   NaN
                 4                CALGDRATGGNNKLTF CASSPDRGEVFF      CALVPSNTNKVVF    CASSLGGENTLYF    NaN
2                3                CALGSNTGYQNFYF   CASTGGGAPLF       CALAPSNTNKVVF    CASSQDPGDYEQYF   NaN
                 4                CALGSNTGYQNFYF   CASTGGGAPLF       CALVPSNTNKVVF    CASSLGGENTLYF    NaN
3                4                CALAPSNTNKVVF    CASSQDPGDYEQYF    CALVPSNTNKVVF    CASSLGGENTLYF    NaN

### Filtering

In [23]:
result = mo.compute_distance_from_dataset(path1=path1, organism="mouse", seq_type="BETA", source="dash")
result

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF           39
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF            47
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF         44
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF          32
                 5                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGKNYNQGKLIF   CASDRAGEQYF            44
...                                                                                                       ...
91               94               CAVSHNYQLIW    CASSGDSNERLFF     CAVSDNYAQGLTF    CASSGGTGASAETLYF       24
                 96               CAVSHNYQLIW    CASSGDSNERLFF     CAVSDNYAQGLTF    CASSFRDSAETLYF         16
92               94               CATDSSSGSWQLIF CASSLGVNERLFF     CAVSDNYAQGLTF    CASSGGTGASAETLYF       28
                 96               CATDSSSGSWQLIF CASSLGVNERLFF     CAVSDNYAQGLTF    CASSFRDSAETLYF         23
94               96               CAVSDNYAQGLTF  CASSGGTGASAETLYF  CAVSDNYAQGLTF    CASSFRDSAETLYF         20

Method
Chain                                                                                                beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      159
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF       183
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF    186
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF     138
                 5                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGKNYNQGKLIF   CASDRAGEQYF       174
...                                                                                                   ...
91               94               CAVSHNYQLIW    CASSGDSNERLFF     CAVSDNYAQGLTF    CASSGGTGASAETLYF  113
                 96               CAVSHNYQLIW    CASSGDSNERLFF     CAVSDNYAQGLTF    CASSFRDSAETLYF     89
92               94               CATDSSSGSWQLIF CASSLGVNERLFF     CAVSDNYAQGLTF    CASSGGTGASAETLYF  118
                 96               CATDSSSGSWQLIF CASSLGVNERLFF     CAVSDNYAQGLTF    CASSFRDSAETLYF    108
94               96               CAVSDNYAQGLTF  CASSGGTGASAETLYF  CAVSDNYAQGLTF    CASSFRDSAETLYF     91

[3403 rows x 2 columns]

In [24]:
com = lambda x, y: x > y
thr = 30
expression = (mo.name, com, thr)
result.filter_result(expression, 'cdr3_b')

Method                                                                                               tcrdist3  \
Chain                                                                                                  cdr3_b
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF           39
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF            47
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF         44
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF          32
                 5                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGKNYNQGKLIF   CASDRAGEQYF            44
...                                                                                                       ...
87               96               CAVSMRYNQGKLIF CASSEGRGGSDYTF    CAVSDNYAQGLTF    CASSFRDSAETLYF         32
88               89               CALGVDTNAYKVIF CASSSPAEQYF       CAVSSNYQLIW      CASSSRQGGSAETLYF       36
                 90               CALGVDTNAYKVIF CASSSPAEQYF       CAVSANYAQGLTF    CASGGRDSAETLYF         36
                 94               CALGVDTNAYKVIF CASSSPAEQYF       CAVSDNYAQGLTF    CASSGGTGASAETLYF       40
                 96               CALGVDTNAYKVIF CASSSPAEQYF       CAVSDNYAQGLTF    CASSFRDSAETLYF         32

Method
Chain                                                                                                beta
(Rep1, recep_id) (Rep2, recep_id) (Rep1, cdr3_a) (Rep1, cdr3_b)    (Rep2, cdr3_a)   (Rep2, cdr3_b)
0                1                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGDRATGGNNKLTF CASSPDRGEVFF      159
                 2                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGSNTGYQNFYF   CASTGGGAPLF       183
                 3                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALAPSNTNKVVF    CASSQDPGDYEQYF    186
                 4                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALVPSNTNKVVF    CASSLGGENTLYF     138
                 5                CAVSLDSNYQLIW  CASSDFDWGGDAETLYF CALGKNYNQGKLIF   CASDRAGEQYF       174
...                                                                                                   ...
87               96               CAVSMRYNQGKLIF CASSEGRGGSDYTF    CAVSDNYAQGLTF    CASSFRDSAETLYF    153
88               89               CALGVDTNAYKVIF CASSSPAEQYF       CAVSSNYQLIW      CASSSRQGGSAETLYF  151
                 90               CALGVDTNAYKVIF CASSSPAEQYF       CAVSANYAQGLTF    CASGGRDSAETLYF    154
                 94               CALGVDTNAYKVIF CASSSPAEQYF       CAVSDNYAQGLTF    CASSGGTGASAETLYF  163
                 96               CALGVDTNAYKVIF CASSSPAEQYF       CAVSDNYAQGLTF    CASSFRDSAETLYF    134

[1348 rows x 2 columns]