In [1]:
from epytope.Core import Protein, Peptide, Allele
from epytope.IO import read_fasta
from epytope.CleavagePrediction import CleavageSitePredictorFactory
from epytope.IO.FileReader import process_dataset_TCR

In [6]:
proteins = read_fasta("/home/mahmoud/Documents/epytope/epytope/epytope/tutorials/data/proteins.fasta", id_position=3, in_type=Protein)
proteins

[PROTEIN: IPVIIERYKGEKQLPVLDKTKFLVPDHVNMSELVKI (aa-seq)
 		  NP_852610_part2 (orig transcript)
 		 VARIANTS:,
 PROTEIN: MKMRFFSSPCGKAAVDPADRCKEVQQIRDQHPSK (aa-seq)
 		  NP_852610.1 (orig transcript)
 		 VARIANTS:]

In [7]:
pcm = CleavageSitePredictorFactory("PCM")
site_result = pcm.predict(proteins)
site_result

                    Seq   pcm
ID              Pos
NP_852610_part2 0     I  0.00
                1     P  0.00
                2     V  0.00
                3     I -1.93
                4     I -0.89
...                  ..   ...
NP_852610.1     29    Q -1.50
                30    H -0.34
                31    P -2.93
                32    S  0.00
                33    K  0.00

[70 rows x 2 columns]

In [12]:
site_result["pcm"]

ID               Pos
NP_852610_part2  0      0.00
                 1      0.00
                 2      0.00
                 3     -1.93
                 4     -0.89
                        ...
NP_852610.1      29    -1.50
                 30    -0.34
                 31    -2.93
                 32     0.00
                 33     0.00
Name: pcm, Length: 70, dtype: float64

In [11]:
comp = lambda x,y: x > y
expressions=[("pcm",comp,0)]


site_result.filter_result(expressions)

                    Seq   pcm
ID              Pos
NP_852610_part2 7     Y  1.26
                10    E  1.19
                13    L  1.18
                17    D  0.51
                29    M  1.07
NP_852610.1     3     R  0.60
                5     F  0.41
                12    A  0.43
                13    A  0.27
                15    D  0.29
                23    V  0.86
                26    I  0.42
                28    D  0.94